services:
  app:
    build: .
    container_name: go-embedded-system-api
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      MONGO_URI: mongodb://mongo:27017
    command: air

  mongo:
    image: mongo:8.0.1
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:

