services:
  app:
    image: golang:1.23.2-bullseye
    container_name: go-api
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    working_dir: /app
    env_file:
      - .env
    command: >
      bash -c '
      go install github.com/air-verse/air@latest
      && air --build.cmd "go build -o tmp/api src/cmd/api/main.go" --build.bin "./tmp/api"
      '